// Generated by CoffeeScript 1.6.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  window.onload = function() {
    var editor, page, s, try2;
    try {
      s = io.connect('http://' + window.location.hostname + '/cmds');
    } catch (error) {
      console.log(error);
    }
    try2 = function() {
      if (typeof s !== 'undefined' && s.socket.connected !== true) {
        try {
          return root.s = s = io.connect('ws://' + window.location.hostname + '/cmds');
        } catch (error) {
          return console.log(error);
        }
      }
    };
    setTimeout(try2(), 1000);
    page = window.location.pathname;
    if (page === "/") {
      editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        mode: "htmlmixed",
        vimMode: true,
        lineNumbers: true,
        tabMode: "indent",
        matchBrackets: true,
        theme: 'monokai'
      });
      editor.focus();
      s.emit('index', {}, function(data) {
        var viewID;
        console.log(data);
        root.vid = viewID = data;
        return $('#viewID')[0].innerHTML = data;
      });
      return editor.on("change", function() {
        return s.emit('update', {
          code: editor.getValue()
        }, function(data) {
          return data = null;
        });
      });
    } else if (page === "/view") {
      $('#view').on('submit', function(e) {
        e.preventDefault();
        return s.emit('view', {
          sid: $('#vid').val()
        }, function(data) {
          $('body').html('connected.');
          return console.log(data);
        });
      });
      return s.on('update', function(data) {
        $('body').html(data.code);
        return console.log(data.code);
      });
    }
  };

}).call(this);
