// Generated by CoffeeScript 1.6.1
(function() {
  var root;

  root = typeof exports === "function" ? exports(this) : void 0;

  window.onload = function() {
    var editor, page, s, try2, url;
    editor = CodeMirror.fromTextArea(document.getElementById("code"), {
      mode: "html",
      lineNumbers: true,
      tabMode: "indent"
    });
    url = window.location.protocol + '//' + window.location.hostname + '/cmds';
    root.s = s = io.connect(url);
    try2 = function() {
      if (typeof s !== 'undefined' && s.socket.connected !== true) {
        return root.s = s = io.connect('ws://' + window.location.hostname + '/cmds');
      }
    };
    setTimeout(try2(), 5000);
    page = window.location.pathname;
    if (page === "/") {
      s.emit('index', {}, function(data) {
        var viewID;
        viewID = data;
        return $('#viewID').html = data;
      });
      return editor.on("change", function() {
        return s.emit('update', {
          code: editor.getValue()
        });
      });
    } else if (page === "/view") {
      return s.on('update', function(data) {
        return $('body').html = data.code;
      });
    }
  };

}).call(this);
